### ISSUE TITLE
Устранить проблему мержа

### ISSUE THREAD

**Issue by ellokopoko** [ellokopoko/prog#10]
Тревис, проблема мержа, разные шаблонизаторы (Haml, erb).
ИСПОЛЬЗУЕМ ВЕЗДЕ ERB (чтоб меньше переделывать)

**Comment by VlasovS** [comment]
Если проблема мержа в том, чтобы все было на одном шаблонизаторе, то я за haml, все переделаю на haml, всё-таки он удобней и интересней. К выполнению задания преступил.

**Comment by VlasovS** [comment]
Готово! В коммите "ERB to HAML" я удалил лишние .erb файлы и заменил их на их .haml альтернативу.
