### ISSUE TITLE
Какие конликты слияния остались?

### ISSUE THREAD

**Issue by ellokopoko** [ellokopoko/prog#20]
Не понятно, что нужно исправить чтоб слиться в главную ветку. Не все комметарии были понятными. Те что поняли исправили.
Максим, поясни пожалуйста еще раз подробно, какие у нас конфликты остались?

**Comment by MasalitinMaksim** [comment]
Ну смотрите, схема такая:
1) Я смотрю, чтобы у вас был рабочим тревис - это залог того, что все ваши тесты, которые есть в приложении проходят
2) Я смотрю, что нет конфликтов мержа - это залог того, что у вас в dev тот код, который вы хотите слить в мастер. Если есть конфликты - их в любом случае нужно будет исправить, соответственно код изменится и станет другим. 

Когда это все иправлено я приверяю ДЗ (в т.ч. на выполенение обязательных правил).
В вашем реквесте https://github.com/ellokopoko/prog/pull/9 я дважды написал про конфликты мержа, думаю, что третий раз уже должно быть очевидно)

**Comment by MasalitinMaksim** [comment]
We can’t automatically merge this pull request. - должно быть Able to merge
 The Travis CI build failed - должно быть success

**Comment by ellokopoko** [comment]
Как проверить конфликт мержа, есть он нет, где смотреть?

**Comment by MasalitinMaksim** [comment]
Внизу написано серым жирным шрифтом We can’t automatically merge this pull request

**Comment by MasalitinMaksim** [comment]
должно быть Able to merge
