### ISSUE TITLE
Нет статики на хероку

### ISSUE THREAD

**Issue by maksmasalitin** [ellokopoko/prog#25]
http://arcane-savannah-9667.herokuapp.com/

**Comment by VerkhoglyadSvetlana** [comment]
вот переделанная версия на хероку. https://teta-project.herokuapp.com/
Полная копия с гита. Но почему-то не работают ссылки между страницами , а
ассеты заработали. Неподскжете из-за чего это может быть?

2015-01-17 16:03 GMT+02:00 MasalitinMaksim notifications@github.com:

**Comment by maksmasalitin** [comment]
Трудно что-то сказать. Лучше всего посмотреть в логи хероку, там должна писаться ошибка по идее

**Comment by maksmasalitin** [comment]
Обновите тогда в ридми ссылку, ок?
